service: sqs-lambda-worker-demo


plugins:
  - serverless-webpack # Use serverless-webpack plugin to transpile ES6/ES7
  - serverless-offline
  # - serverless-domain-manager
  # - serverless-plugin-aws-alerts

custom:
  stage: ${opt:stage, 'dev'}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'yarn'
    package:
        individually: true #Webpack compiles and optimizes each function individually,
        # removing unnecessary imports and reducing code sizes significantly

provider:
  name: aws
  runtime: nodejs8.10
  environment:
      # QUEUE: ${ssm:/${self:custom.stage}/sqs-lambda/queue-name~true}

# you can overwrite defaults here
#  stage: dev
  region: ap-southeast-2


functions:
  worker:
    handler: src/worker.default
    description: worker fn consuming from sqs
    reservedConcurrency: 5
  producer:
    handler: src/producer.default
